### ISSUE TITLE
cant scroll down to view all building materials?

### ISSUE THREAD

**Issue by FatherA9303** [The-Bees-Decree-Server/VALKEA#17]
is there a certain key i have press or is this a bug

**Comment by The-Bees-Decree-Server** [comment]
> is there a certain key i have press or is this a bug

This should not ben an issue if you are using the mod stock without some kind of combination hammer mod.
You may be using page-able or something similar which may affect the tabs/scrolling.

We just tested and have no issue with scrolling since the hammer table left stock does not need to scroll.
We have purposefully spread out the items to make sure they only take up vanilla space per tab.

**Comment by The-Bees-Decree-Server** [comment]
> is there a certain key i have press or is this a bug

No, it is a conflict you have with another mod. Most likely any mod that affects hammers, hammer positions, hammer tables etc.
Valkea does not have this issue when used without other hammer mods.
